#!/bin/bash
#
###############################################################################
# oneline daemon service 
# URL: https://github.com/nadirhamid/oneline
# Email:matrix.nad@gmail.com
###############################################################################
#
### BEGIN INIT INFO
# Provides:          oneline 
# Short-Description: Oneline server daemon
# Description:       The daemon behind oneline's server
### END INIT INFO
#

RETVAL=0
PIDOF=pidof

if [ -f /etc/SuSE-release ]; then
	. /etc/rc.status
	rc_reset
fi


# See how we were called.
case "$1" in
  start)
	echo -n "Starting oneline server:"
	onelined --start
	exit;
	;;
  stop)
	echo -n "Stopping oneline server:"
	onelined --stop
	;;
  *)
	onelined --start
	echo "Usage: /etc/init.d/oneline start|stop|restart"
	exit 1
esac

exit $RETVAL

