#!/bin/bash
#
###############################################################################
# oneline daemon service 
# URL: https://github.com/nadirhamid/oneline
# Email:matrix.nad@gmail.com
###############################################################################
#
# chkconfig: 2345 20 75
# description: Oneline Server 
#
### BEGIN INIT INFO
# Provides:          oneline 
# Short-Description: Oneline server daemon
# Description:       The daemon behind oneline's server
### END INIT INFO
#

RETVAL=0
PIDOF=pidof

if [ -f /etc/SuSE-release ]; then
	. /etc/rc.status
	rc_reset
fi


# See how we were called.
case "$1" in
  start)
	echo -n "Starting oneline server:"
	oneline-server --start
	exit;
	;;
  stop)
	echo -n "Stopping oneline server:"
	oneline-server --stop
	;;
  status)
        echo -n "Status of lfd:"
        ;;
  restart|force-reload)
	oneline-server --restart
	;;
  *)

  sleep 10
	oneline-server --start
	echo "Usage: /etc/init.d/lfd start|stop|restart|force-reload|status"
	exit 1
esac

exit $RETVAL

