#!/bin/bash
#
###############################################################################
# oneline service 
# URL: http://www.configserver.com
# Email: sales@waytotheweb.com
###############################################################################
#
# chkconfig: 2345 20 75
# description: Oneline Server 
#
### BEGIN INIT INFO
# Provides:          lfd
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: csf Login Failure Daemon (lfd)
# Description:       csf Login Failure Daemon (lfd) init script
### END INIT INFO
#

RETVAL=0
PIDOF=pidof

if [ -f /etc/SuSE-release ]; then
	. /etc/rc.status
	rc_reset
fi

# See how we were called.
case "$1" in
  start)
	echo -n "Starting oneline server:"
	oneline-server --start
	exit;
	;;
  stop)
	echo -n "Stopping oneline server:"
	oneline-server --stop
	;;
  status)
        echo -n "Status of lfd:"
        ;;
  restart|force-reload)
	oneline-server --restart
	;;
  *)
	oneline-server --start
	echo "Usage: /etc/init.d/lfd start|stop|restart|force-reload|status"
	exit 1
esac

exit $RETVAL

